package minicp.search;


public class ChoiceCombinator implements Choice {

    private minicp.search.Choice [] choices;

    public ChoiceCombinator(minicp.search.Choice ... choices) {
        this.choices = choices;
    }

    @Override
    public Alternative[] call() {
        // TODO: return the alternatives generated by the first non empty choice
        return Selector.TRUE;
    }
}